# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: "NorbergFilip"
  email_provider_password: "Forlan21"
  domain_name: example.com
  mailchimp_api_key: "474068e255bb7ad88f2897ffda410153-us14"
  mailchimp_list_id: "3d9982c9e6"
  owner_email: "filipnorberg21@gmail.com"
  secret_key_base: very_long_random_string
  secret_key_base: 2059b7d2a6c37faa82741aae691b6f19536eec883992a73025d5359c02ea565d9986d3b1980748b30d2040fb4fe7b5dd9d36e486bcaf2aff97cef4e5892718e6

test:
  secret_key_base: 03690a74482ae4a6ad7fa536e0a2e0fc23c0ddd21ba1aeca0cb8b20d7308f5249f6367495c6f116a3a8cb2d58a738bc659a37447eb1c15c8442e14db56119843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
